### ISSUE TITLE
Implement ListView template

### ISSUE THREAD

**Issue by rigor789** [rigor789/nativescript-vue#10]
There is currently no way to specify item templates inside ListViews

**Comment by rigor789** [comment]
My idea for the solution is to have a <list-view> component, with a slot. Have yet to explore the details on how to tackle this, but seems like the most reasonable way to go about it!

Other concern is multiple item templates, which I don't know how will work yet.

If you have any ideas or suggestions, please write them down here! Even if it's just brainstorming, really helps with coming up with solutions.

**Comment by vjoao** [comment]
The angular renderer implements it with a detached container element for item templates:
https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/directives/list-view-comp.ts

**Comment by rigor789** [comment]
If I wanted to set the [itemTemplate](http://docs.nativescript.org/api-reference/classes/_ui_list_view_.listview.html#itemtemplate) on the ListView, what gets passed? According to the docs, it can either be a string or a [Template](http://docs.nativescript.org/api-reference/interfaces/_ui_core_view_.template.html). Is a detached container considered a template (Detached Container is a [ProxyViewContainer](http://docs.nativescript.org/api-reference/classes/_ui_proxy_view_container_.proxyviewcontainer.html)?

(Mostly leaving these links here so it's easier to find!)

**Comment by vjoao** [comment]
Yes, Detached Container is a ProxyViewContainer
https://github.com/NativeScript/nativescript-angular/blob/fa089aa67f82c66dd2c37f25b5aca6deed5244e3/nativescript-angular/element-registry.ts#L111

**Comment by vjoao** [comment]
When you pass a String or a Template to itemTemplate, it gets passed to the `builder.parse` function for it to return a View.

https://github.com/NativeScript/NativeScript/blob/master/tns-core-modules/ui/builder/builder.ts#L27

**Comment by rigor789** [comment]
So it expects xml in that case? I think we should pass it a template instead of generating xml that will get parsed again.

**Comment by rigor789** [comment]
On the vue side, after a quick read through docs, I think we need to use (scoped slots)[https://vuejs.org/v2/guide/components.html#Scoped-Slots]
