### ISSUE TITLE
Implement ActionBar component

### ISSUE THREAD

**Issue by rigor789** [rigor789/nativescript-vue#13]
ActionBar should be implemented similarly to ListViews, probably in a custom component.

Discussion about the solution should be in #10, since to keep it in one place!

**Comment by tjvantoll** [comment]
Minor note: might want to rename from AppBar to ActionBar, as that’s the name NativeScript uses.

**Comment by tjvantoll** [comment]
Minor note: might want to rename from AppBar to ActionBar, as that’s the name NativeScript uses.

**Comment by EddyVerbruggen** [comment]
Working on this one atm!

**Comment by EddyVerbruggen** [comment]
This will be the API. Working nicely now on iOS and Android, but will need to test a few more things before creating a PR:

```html
<action-bar :title="subreddit">
  <action-item android.systemIcon="ic_menu_refresh" ios.systemIcon="13" @tap="refresh"></action-item>
  <action-item text="change" android.position="popup" ios.position="right" @tap="chooseSubreddit"></action-item>
</action-bar>
```

**Comment by rigor789** [comment]
Very nice @EddyVerbruggen! Can't wait to test that :)

**Comment by EddyVerbruggen** [comment]
Would be cool if you could take a look, @rigor789!

I've adjusted the listview and tab samples to include an `action-bar`, making them look like this:

![simulator screen shot 1 aug 2017 09 56 40](https://user-images.githubusercontent.com/1426370/28815571-1be74d94-76a2-11e7-8b49-ca850bc4fb42.png)
![simulator screen shot 1 aug 2017 09 58 14](https://user-images.githubusercontent.com/1426370/28815572-1be829c6-76a2-11e7-80f2-dd229456717d.png)
![screenshot_20170801-100710](https://user-images.githubusercontent.com/1426370/28815573-1be9fe04-76a2-11e7-9b4b-0a15dc7032d9.png)

**Comment by rigor789** [comment]
This has been added in #34 

If any issues arise, open a new issue. Closing this one
