### ISSUE TITLE
Review v-model directive.

### ISSUE THREAD

**Issue by rigor789** [rigor789/nativescript-vue#15]
The initial v-model code registers listeners for all possible value types, that should probably be refactored to only register the ones that are actually needed by the element.

For example
`<text-field v-model="test"></text-field>`
Needs to set the `text` prop to the value of `test`, and listen for `textChange` event.

But
`<slider v-model="test2"></slider >`
Needs to set the `value` prop to the value of  `test2`, and listen for `valueChange` event.

Etc.

**Comment by vjoao** [comment]
Could be done just like the web: filter by tag name and attach the proper handlers.

**Comment by rigor789** [comment]
That's possible, but thinking about it, we might just use ViewMeta! That way, when elements are registered, they specify which prop and event is used for v-model!

**Comment by vjoao** [comment]
That would be even cooler =)
