### ISSUE TITLE
Add support to open modal pages

### ISSUE THREAD

**Issue by rigor789** [rigor789/nativescript-vue#19]
Related to #18 

Add support for showing components in a modal.

Also allow passing in data.

**Comment by rigor789** [comment]
WIP https://github.com/rigor789/nativescript-vue/commit/572dc3a936a5aebb066defc33ca185a048e62850

**Comment by rigor789** [comment]
This is now added, and working.

**Comment by banunn** [comment]
Is there documentation or a code demo we could see for using the Modal Page within a Vue Instance?

**Comment by rigor789** [comment]
@banunn https://nativescript-vue.org/en/docs/routing/manual-routing/#showmodal
