### ISSUE TITLE
iOS tap issue

### ISSUE THREAD

**Issue by jlooper** [rigor789/nativescript-vue#24]
when tapping any element on the sample apps, the app crashes:

```
*** Assertion failure in -[UIGestureGraphEdge initWithLabel:sourceNode:targetNode:directed:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit_Sim/UIKit-3600.7.47/Source/GestureGraph/UIGestureGraphEdge.m:25
Jun  2 14:11:03 LOOPERMAC com.apple.CoreSimulator.SimDevice.1658C660-8802-4075-8603-2A0148C48692.launchd_sim[14161] (UIKitApplication:org.nativescript.vuesample[0x30e8][14183][43417]): Service exited due to Segmentation fault: 11
```

**Comment by tjvantoll** [comment]
I’m hitting this error as well on a number of the samples. Very odd that there’s not more debugging information.

**Comment by rigor789** [comment]
This is most likely the same bug that causes app to crash on `garbage collection`. As far as I know it is being  tracked by the NativeScript team working on the debugger!

**Comment by vakrilov** [comment]
I got the exact same exception yesterday. @rigor789 do you know if there is related issue somewhere in the NS repos - I could take a look.

**Comment by rigor789** [comment]
@vakrilov not that I know of. I have been talking to @bundyo about an issue with `gc()` but not sure if there is an issue open anywhere.

**Comment by vakrilov** [comment]
Found something worth sharing - It seems that the app crashes when an event is attached on a view inside a scroll. The simplest reproduce I got was that:

```
template: `
    <page>
        <stack-layout>
            <button @tap="onTap">Will Work</button>
            <scroll-view>
                <button @tap="onTap">Will Crash</button>
            </scroll-view>
        </stack-layout>
    </page>
`
```
The example with the list-view also crashes and again - the list view is scrollable.
Still no idea why this happens, but still interesting similarity.

**Comment by bundyo** [comment]
The issue Igor mentions was only in Android - the app crashed on garbage collection - I've reported it to Peter Kanev (@Pip3r4o) and he said that he reproduced it and tracked down its reason. No idea if the issue is logged though. Also not sure if this is the same issue as iOS runtime architecture is different.

**Comment by rigor789** [comment]
Interesting that it seems to happen in a `scroll-view` with events attached. Does it crash instantly, or after scrolling the `scroll-view` @vakrilov? I guess if it crashes after scrolling, that it might be due to some `gc()` issue?

**Comment by vakrilov** [comment]
It crashes instantly so I don't think its a GC issue. UIGestureGraphEdge in the error above and the fact that Scroll/list-view handle touches makes me think it is gesture-related.
I also tried to reproduce the crash in a non-vue project with the same UI elements - I couldn't. So I guess the order in which the views are added is the difference and what's causing the crash.

**Comment by lewebsimple** [comment]
I get the same error using a ListView inside a DockLayout with 1.3.1, which is strange because it appears to have been fixed.

**Comment by lewebsimple** [comment]
Update: It crashes on iOS 11.x (simulator) but not iOS 9.x (physical device)

**Comment by sudhanshu-15** [comment]
I am facing the same issue buttons inside a scroll view. Haven't tested on a physical device.

**Comment by xlcrr** [comment]
Same problem =[

**Comment by eladcandroid** [comment]
+1
