### ISSUE TITLE
Change Tracking Not Working inside list-view

### ISSUE THREAD

**Issue by vakrilov** [rigor789/nativescript-vue#31]
It seems that changing the items set to a list view will not cause re-render.
Here is a sample comparing `list-view` vs. `v-for`:
```
const Vue = require('nativescript-vue/dist/index')
new Vue({
    data: {
        items: [
            { value: "first value" },
            { value: "second value" }
        ]
    },

    template: `
        <page>
            <grid-layout columns="* *" rows="* auto">
                <stack-layout>
                    <label v-for="item in items" key="item.id" :text="item.value"></label>
                </stack-layout>

                <list-view :items="items" col="1">
                    <template scope="item">
                         <label :text="item.value"></label>
                    </template>
                </list-view>

                <button text="update" @tap="update()" row="1" colSpan="2"></button>
            </grid-layout>
        </page>
    `,

    methods: {
        update() {
            this.items.forEach(function(item) {
                item.value += "!";
            });
        }
    }
}).$start()
```
The update method will not cause an update in the list view:
![list-view bug](https://user-images.githubusercontent.com/4092076/27997695-b3790542-6506-11e7-8ca1-c45929214902.gif)

The reason for this behavior is probably that the `item` passed to the list view template is [actually a copy of the original item](https://github.com/rigor789/nativescript-vue/blob/master/platform/nativescript/runtime/components/list-view.js#L138-L149). This also means that changing the copy of the item from inside the list view template, will not affect the original item.

Any thoughts on how what is the right behavior or if VueJS suggests some other approach at all?

**Comment by rigor789** [comment]
We can probably make the `ItemContext` into a watcher, I will look into it!

**Comment by saknarak** [comment]
I'm run into same problem too. any work around?

**Comment by rigor789** [comment]
I'm currently working on a fix, I haven't figure it out yet, but hopefully I'll get it fixed!
