### ISSUE TITLE
<page> works; <Page> doesn’t

### ISSUE THREAD

**Issue by tjvantoll** [rigor789/nativescript-vue#36]
I was testing out @EddyVerbruggen’s changes that add ActionBar support, which work great btw, and I noticed one small thing.

This works: (`<page>`)

```
const Vue = require("nativescript-vue");

new Vue({
  template: `
    <page>
      <ActionBar title="❤️ Vue ❤️"></ActionBar>
      <StackLayout></StackLayout>
    </page>
  `
}).$start();
```

This doesn’t: (`<Page>`)

```
const Vue = require("nativescript-vue");

new Vue({
  template: `
    <Page>
      <ActionBar title="❤️ Vue ❤️"></ActionBar>
      <StackLayout></StackLayout>
    </Page>
  `
}).$start();
```

In NativeScript we support both so both should work here. Personally I prefer uppercase tag names. Not sure if this is related to the ActionBar commit or not.

**Comment by rigor789** [comment]
Yep, that's related to my change to ActionBar. I will fix this today when i get a chance.

**Comment by tjvantoll** [comment]
@rigor789 No worries. Also, my app keeps crashing on Android with the latest code from master. Just an fyi.

**Comment by EddyVerbruggen** [comment]
@rigor789 Allow me to fix that as I need to commit an enhancement to the ActionBar code anyway. #piggyback

**Comment by rigor789** [comment]
Sure, feel free to fix it.
