### ISSUE TITLE
Using nativescript-vue with render functions/JSX

### ISSUE THREAD

**Issue by ajoslin** [rigor789/nativescript-vue#44]
I'm interested in using this (and probably contributing), but I'm having a hard time finding where exactly the nativescript components are wrapped in Vue components.

I'm seeing that `element-registry` adds  Nativescript components to a map with tag name keys (eg `stack-layout` -> `ui/layouts/stack-layout`). 

However, I can't find how/where I could get a direct reference to the Vue versions of these components, so I can use the Vue 2+ `render` function with JSX syntax:

```js
import {Page, ScrollView, StackLayout} from 'vue-nativescript/exported-native-components'

const App = new Vue({
  render: (h) {
    return <Page>
      <ScrollView>
        <StackLayout>
          some content..
        </StackLayout>
      </ScrollView> 
    </Page>
  }
}) 
```

Would it be possible to add these exports? I'd love to open a PR, but I'm not sure where atm. 

I don't know where exactly in the codebase the Vue compiler is told "hey, these new Nativescript components exist with these tag-names".

**Comment by ajoslin** [comment]
Ideally, it would be easy to get references to Vue wrappers. Eg:

```js
const Page = Vue.registerElement('page', () => require('ui/page'))
const myCmp = {
  render (h) { return <Page /> }
}
```

Again, I'd love to contribute, I'm just not sure where yet. If you could point me in the right direction...

**Comment by rigor789** [comment]
Hey @ajoslin I'm not sure how the JSX part of it works, but these elements aren't actual vue components, these are the "platform" elements, that vue just acknowledges, think of it like HTML, the `div`, `strong` etc. are just the elements that the platform supports, there is no vue component associated with those.

Ideally jsx should just work without needing to import these, but again, I'm not sure how the jsx implementation works.

**Comment by ajoslin** [comment]
Alright. I'm still very new to Vue and I'm trying to avoid the template magic (so I don't have to learn it!) and just stay with hyperscript/jsx form.

I assumed the JSX needs a reference to the component instance. But it looks like the hyperscript doesn't. I'll play with this some more, thanks.
