### ISSUE TITLE
Vuex ???

### ISSUE THREAD

**Issue by markomiljkovic** [rigor789/nativescript-vue#46]
Does it have a support for Vuex and how do you implement it, Im running into errors when Im trying to implment it ????

**Comment by rigor789** [comment]
Hey, it should be working, but I have yet to try it. Can you describe the issues you are facing?

**Comment by lakexyde** [comment]
It doesn't work the normal way. However this was how I got it to work:

Use Vuex:

```Vue.use(Vuex)```

import your store:

```const store = require('./path/to/store.js');```

And the just before creating your Vue instance:

```Vue.prototype.$store = store```

This makes your Vuex store available anywhere usin ```this.$store``` in your components.

Hope this helps.

**Comment by rigor789** [comment]
I just tested this with the latest version, and it seems like the workaround is no longer necessary.
