### ISSUE TITLE
router-page: the first transition is not caught for the Android button back

### ISSUE THREAD

**Issue by newapx** [rigor789/nativescript-vue#55]
I used `<router-page>`.  (`"nativescript-vue": "^0.1.10",`)
On Android the hardware button works back only after the second transition, for navigation used `$router.push`

**Comment by newapx** [comment]
I install version 0.1.12 and this problem is solved by use of $navigateTo, but when using $navigateBack components from which return is realized remains in memory and does not destroy that leads to memory leaks

**Comment by rigor789** [comment]
You are right, we need to address cleaning up. I also need to rework the page routing...

**Comment by newapx** [comment]
Memory leak can be excluded having inserted a code into function `Vue.prototype.$navigateTo`
```
      toPage.disposeNativeView = function(){
        vm.$destroy();
      }
```

**Comment by blackss2** [comment]
I handle router with this way.
https://github.com/rigor789/nativescript-vue/issues/68

**Comment by rigor789** [comment]
The memory leak and back nav should be working in the latest code (not published to npm at this time yet)
