### ISSUE TITLE
Bug when re-opening the android app with the app icon.

### ISSUE THREAD

**Issue by tralves** [rigor789/nativescript-vue#59]
**Steps to reproduce:**

1. If you open an app
2. Close it with the Android back physical button
3. Open it again through the app icon

**Expected**

The app opens normaly

**Result**

You get the error:

![screen shot 2017-10-09 at 10 58 19](https://user-images.githubusercontent.com/2600867/31341775-fe480c7c-ace0-11e7-9211-a2717c8fea37.png)

This error happened with both the [Groceries Vue app](https://github.com/tralves/groceries-ns-vue) and the [ui-tests app](https://github.com/rigor789/nativescript-vue-ui-tests).

**Comment by blackss2** [comment]
I have same problem and you can fix that problem with this boiler plate way.
After apply it, you should remove **{PROJECT_DIR}/platforms/android/build/outputs/apk/YOURAPP-debug.apk** and restart

https://github.com/NativeScript/NativeScript/issues/4960

**Comment by rigor789** [comment]
Just for reference here is the Activity lifecycle diagram, I think we need to implement android specific behavior (hook into the lifecycle) to handle resumed activities: https://developer.android.com/guide/components/activities/activity-lifecycle.html#alc

**Comment by seohangyu** [comment]
@blackss2  
I tried with the release. But still bugs happen.

**Comment by blackss2** [comment]
Try this
https://github.com/rigor789/nativescript-vue/issues/78
