### ISSUE TITLE
iOS: ver 0.1.22: the event "destroyed" does not fired

### ISSUE THREAD

**Issue by newapx** [rigor789/nativescript-vue#67]
After a call of `$navigateBack` event `destroyed` at a component is not caused. 
Event `mounted` worked.

It (both event) works at Android.

**Comment by rigor789** [comment]
I wonder if that is intentional by Vue, maybe it is in SSR mode when not running in a browser:

https://vuejs.org/v2/api/#destroyed
> This hook is not called during server-side rendering.

**Comment by newapx** [comment]
According to documentation all hook do not work in the SSR mode, but `mounted` works.
And all works fine at Android.

Similar to operations of NS on iOS.

**Comment by rigor789** [comment]
Alright, thanks for the info, will look into it

**Comment by rigor789** [comment]
I have released `0.1.24` and I believe instances should get destroyed properly now, can you please give it a try and let me know?

**Comment by newapx** [comment]
I have checked on version 0.2.0.
The page is destroyed, and the event "ondestroy" also works

**Comment by rigor789** [comment]
Cool!
