### ISSUE TITLE
Is it support vue with typescript?

### ISSUE THREAD

**Issue by duxiaofeng-github** [rigor789/nativescript-vue#71]
Like angular version's nativescript, it can work with typescript well. So, is there any possiable to let typescript version's vue work with this plugin?

**Comment by tralves** [comment]
I don't see why not, specially when Vue 2.5 has first class support. That would not have anything to do with the plugin itself but with the build process.

I want to add TS support to the webpack template soon.

**Comment by rigor789** [comment]
This should be solved in a template (unless we need to introduce some changes to the core). Closing the issue for now.
