### ISSUE TITLE
suggest : v-show

### ISSUE THREAD

**Issue by blackss2** [rigor789/nativescript-vue#77]
As I know, v-if is not working properly.
So I made this custom v-show with simple directive.
only problem it has is sub components' conditions are evaluated.

```javascript
Vue.directive('show', {
	inserted: function (el, attr) {
		el.setAttribute("visibility", attr.value ? "visible" : "collapsed");
	},
	update: function (el, attr) {
		el.setAttribute("visibility", attr.value ? "visible" : "collapsed");
	}
});
```

**Comment by rigor789** [comment]
I've added the `v-show` directive, could you elaborate what you mean by 
> only problem it has is sub components' conditions are evaluated.

**Comment by blackss2** [comment]
difference of v-if and v-show is [condtion statement on sub node is pre estimated or not].
v-if not estimate sub nodes if condition is false,
but v-show estimate all sub nodes always.
currently nativescript-vue's if not working properly, we should use v-show.
but if you use v-show, you should know sub node should have robust to own condition(obj.is_on -> obj && obj.is_on)

**Comment by rigor789** [comment]
That is the expected behavior of v-show, it only hides thing visually. As for v-if not working, can you show me an example? I know it had issues in an action-bar but i think that's an edge case.

**Comment by blackss2** [comment]
i misunderstand v-if is not working all part, cuz i use v-if only action bar.

**Comment by rigor789** [comment]
For the action-bar, you might solve it like I did: https://github.com/rigor789/nativescript-vue/issues/76#issuecomment-345309105

Not the most ideal, but works
