### ISSUE TITLE
ActionBar Hidden on Android Emulator but Gap Remains to be removed

### ISSUE THREAD

**Issue by irthos** [rigor789/nativescript-vue#84]
After much tinkering, the action bar is hidden but my content only goes to the bottom of where it was. In the following example, notice the space before a custom nav component displays [Example of issue](https://dl2.pushbulletusercontent.com/HNYtsZHDjoYxCXOkRogs3IhCrAMyue83/Screen%20Shot%202017-11-17%20at%203.25.32%20PM.png)

Is anyone having trouble setting, styling, and removing the action bar? This seems like a tricky operation for me and think there might be some disconnect between rollup and tns build. I've hacked various style.xml files to comment out anything with toolbar or actionbar, leaving just 
`    <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    </style>
`

I'm sure there's a right way to do this and pretty sure I'm not doing it. When I remove the page attributes below, the action bar doesn't reappear so I'm feeling a bit lost in what is actually doing work. I've removed and re-added the android platform, tns build, etc and nothing is indicating causality!

My template on main.js is:
```
  template: `
    <page ref="page" actionBarHidden="true" backgroundSpanUnderStatusBar="false" :class="pageClasses">
      <absolute-layout class="splash" top="0" bottom="0" right="0" left="0">
        <router-view></router-view>
      </absolute-layout>
    </page>
    `,
```

**Comment by rigor789** [comment]
Can you try and reproduce it on https://play.nativescript.org/?template=play-vue ? 

I just tried this, and I don't see any extra space above the label: https://play.nativescript.org/?template=play-vue&id=5wbEvdsl-w0Y9JNUJjiw0

**Comment by irthos** [comment]
Thanks. My app's too convoluted to put up there right now. I'll try a fresh installation and see if that solves it before investing the time to mirror on playground. Btw, I'm using the Nativescript-Vue Grocery example as a starter so there may be artifacts that won't apply to a fresh install. Will be back soon.

**Comment by irthos** [comment]
Can't reproduce with a fresh install (rollup template). Let's close this unless anyone else runs into a similar issue. Appreciate the attention!
