### ISSUE TITLE
android studio build error asbg:runAstParser

### ISSUE THREAD

**Issue by seohangyu** [rigor789/nativescript-vue#88]
'nativescript-vue-rollup-template' is being used.
 cd <project_name> -> cd tns -> tns run There is no problem with android.
 However, using 'android-stuido' causes the following problems in the build:

Execution failed for task ':asbg:runAstParser'
java.io.IOException: Cannot run program "node": error=2, No such file or directory

There are many such issues on Google, but the correct solution is not presented.
How to solve it?

**Comment by rigor789** [comment]
Looks like it can't find the node executable, you might need to set up the correct paths either system wide (which I assume is already set up because you can run tns commands) or within Android Studio. I haven't used it too much so I don't really know where you need to set it up.

**Comment by seohangyu** [comment]
I solved it with an absolute path, but there were still other problems with errors. The Android studio seems to have been created without consideration. Other templates will not build as well. When testing, do you usually run the emulator on your Android studio using the 'tns command'?

**Comment by rigor789** [comment]
I use the `tns run android` command only, I did not find any need for using the android studio for running my app.

**Comment by seohangyu** [comment]
So how do you run different kinds of emulators? The emulator must be turned on to see the tns device command.

**Comment by rigor789** [comment]
I use GenyMotion (on linux) and I just start it manually before running the command, or if I'm at my desk, I just plug in a phone that I use for development, because it's faster than an emulator.
