### ISSUE TITLE
 How do I move a page? Is it only possible with a router?

### ISSUE THREAD

**Issue by seohangyu** [rigor789/nativescript-vue#91]
How do I move a page? Is it only possible with a router?
 If I can only do it as a router, how do I handle backlinks?

**Comment by rigor789** [comment]
Can you please let me know what you mean by moving a page? If you mean navigating to different pages you can use `this.$navigateTo(<page or component>, options, pageCb)` (source: https://github.com/rigor789/nativescript-vue/blob/master/platform/nativescript/plugins/navigator-plugin.js#L14)

**Comment by seohangyu** [comment]
What I was talking about was something like 'navigate'. Moving the view on the screen. Where should you refer to a simple example of what you're linking to?

**Comment by rigor789** [comment]
Here is a simple example: https://github.com/rigor789/nativescript-vue/blob/master/samples/app/app-with-pages.js

**Comment by seohangyu** [comment]
@rigor789  thx!
