### ISSUE TITLE
 Image does not appear

### ISSUE THREAD

**Issue by seohangyu** [rigor789/nativescript-vue#92]
Image does not appear

I do not think there is a problem in the path. What is the problem?
 Likewise, putting it in 'App_resources' folder and using 'res' does not appear when called. The image will only appear via http url.

![2017-11-29 1 52 44](https://user-images.githubusercontent.com/23069763/33358658-44a37af4-d50d-11e7-8fb4-fb1a509ee366.png)

![2017-11-29 1 56 21](https://user-images.githubusercontent.com/23069763/33358632-210e6a86-d50d-11e7-96ec-ff9f6d604fbf.png)

what`s the problem?

**Comment by rigor789** [comment]
Have you tried `~/images/logo_400.png`?

**Comment by seohangyu** [comment]
sure but not appear

**Comment by rigor789** [comment]
Are you using the rollup / webpack template? With the pure js version it works as expected

**Comment by seohangyu** [comment]
I am using the rollup template. 
Is this the cause?

**Comment by tralves** [comment]
I think so. Try adding the image to `tns\app\images\logo_400.png`.

**Comment by seohangyu** [comment]
Thanks and Resolved! 
From the following link
https://github.com/tralves/nativescript-vue-rollup-template/issues/7#issuecomment-347837776
