### ISSUE TITLE
Router Bug (tested on IOS)

### ISSUE THREAD

**Issue by Skyhark-Projects** [rigor789/nativescript-vue#96]
Hi,

Their is a bug with the router-view. 

When I try to start your sample app with the router view only the content of the router-view is displayed.

The wrapper around the router-view with the navigation buttons are not displayed.

I attached a picture of what I got with your sample app when I run on IOS.

I also tried with a custom app and got the same result.

When I disable the overwritten $start function of the router plugin, It works again.

<img width="382" alt="screen shot 2017-11-30 at 12 34 42" src="https://user-images.githubusercontent.com/28492958/33428946-2a29beb8-d5cb-11e7-8f05-4342be89721d.png">

**Comment by rigor789** [comment]
I have done some large modifications to the routing, but I have yet to add a flag that disables page-routing related code when not used. I'm assuming you are trying to use a `<router-view />` (component based routing on the same page) which is not working properly. If you are trying to use page routing, then you will need to provide the action-bar for every page that you can route to.

**Comment by aaronksaunders** [comment]
@rigor789 can you point to a specific example on how to get routing to work?

**Comment by rigor789** [comment]
Closing this in favor of #98 because I'm almost certain that it's the same issue.

@aaronksaunders `app-with-router-pages.js` should be working in the repo, so take a look here: https://github.com/rigor789/nativescript-vue/blob/master/samples/app/app-with-router-pages.js

(sorry for the slow response, I have so many things going on...)

**Comment by aaronksaunders** [comment]
Will check it out today, thanks
